{
    integer func func4  = {
        integer func func4 = {
            integer func func4 = {
                integer func func4 = {
                    var x : integer;
                    x := 1984;
                    x
                }
                ;
                put func4;
                4891
            }
            ;
            put func4;
            1984
        }
        ;
        put func4;
        4891
    }
    ;
    put func4
}